### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by frol** [nearprotocol/token-contract-as#3]
Even after a manual fix of #2, I sill don't understand the expected flow. I blindly executed `yarn start` (as per the documentation), and the following error message is shown:

```
Starting deployment. Account id: near-hello-devnet, node: https://rpc.nearprotocol.com, helper: undefined, file: ./dist/main.wasm
Error:  TypedError: Can not sign transactions for account near-hello-devnet, no matching key pair found in Signer.
```

**Comment by willemneal** [comment]
Yeah this is the same issue across the board currently with our examples.  Particularly the ones that were one near studio.  

I have a PR here: https://github.com/nearprotocol/counter/pull/1

That currently runs with `yarn dev`, but it unfortunately runs out of gas after the first increment.

We have also decided that the default folder for binary artifacts in `out/`, so somewhere in the config it should be changed in this project to reflect that.

**Comment by janedegtiareva** [comment]
fixed.
